import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "sonner";
import { validateRequest } from "@/lib/auth";
import { ViewTransitions } from 'next-view-transitions'


export const metadata: Metadata = {
  title: "YouTube Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await validateRequest()
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={GeistSans.className}>
          <Navbar />
          {children}
          <Toaster richColors />
        </body>
      </html>
    </ViewTransitions>
  );
}
